### ISSUE TITLE
download function didn't work.

### ISSUE THREAD

**Issue by pr1n4ple** [huxinghai1988/fastdfs-client-ruby#1]
the file download isn't match what i upload.

**Comment by huxinghai1988** [comment]
download has been a success, file isn't you upload

**Comment by pr1n4ple** [comment]
other questions, i can't upload File object success,but i can upload Tempfile object successful. what i done wrong ?

**Comment by huxinghai1988** [comment]
can you speak chinese

**Comment by pr1n4ple** [comment]
file_insert = @storage.upload(File.new(File.expand_path("../1.txt", __FILE__))) 
i code like this ,but it can't work.
/usr/local/lib/ruby/gems/2.3.0/gems/fastdfs-client-1.2.0/lib/fastdfs-client/socket.rb:47:in `recv': execution expired (Timeout::Error)

but i can upload Tempfile successful.
fastDSF version is 5.08

**Comment by pr1n4ple** [comment]
卧槽.我上传文件用 File类的对象怎么上传不上去呢.  用Tempfile类的对象就可以.

**Comment by huxinghai1988** [comment]
可能是上次升级的问题，你可以先使用1.0.2 版本， 1.2.0版本确实有点问题！修复后我再通知你更新

**Comment by pr1n4ple** [comment]
好的.我试一试.多谢

**Comment by pr1n4ple** [comment]
还有一个问题.我现在用的1.0.2版本.  这个版本的File类的对象是可以正常上传下载的. 但是Tempfile对象还是由问题..

**Comment by pr1n4ple** [comment]
我刚看了一下存储的文件,是上传的问题.

**Comment by pr1n4ple** [comment]
FILE = Tempfile.new(['1','.jpg'])  使用这种方式创建的临时文件是可以的.  我猜测可能是临时文件扩展名太长的原因,

**Comment by huxinghai1988** [comment]
这个我测试一下先

**Comment by pr1n4ple** [comment]
这个我刚刚又试了 FILE = Tempfile.new('1')  这个方式,这样也没问题.    FILE = Tempfile.new('1.txt')  是有问题的. 你可以试试这个方式.

**Comment by huxinghai1988** [comment]
👌

**Comment by huxinghai1988** [comment]
这些bug已经修复了升级到1.3.0，谢谢你反馈的这些问题，如果后续遇到问题可以继续反馈。
