### ISSUE TITLE
storage 没有dispose

### ISSUE THREAD

**Issue by pr1n4ple** [huxinghai1988/fastdfs-client-ruby#2]
Hi,
   刚刚发现storage类没有dispose函数.
   这样导致连接超过253个之后无法获得新的storage.
   

使用storage.socket.close后就可以了.
虽然正式用的时候不这么用,...

**Comment by huxinghai1988** [comment]
你是说tracker get_storage获取storage 有时候不是Storage对象， 253连接是get_storage的连接吗？

**Comment by pr1n4ple** [comment]
是get_storage 获得的.  多了之后就链接不上了.

**Comment by huxinghai1988** [comment]
明白

**Comment by huxinghai1988** [comment]
你要加一个判断，因为get_storage是没有获取tracker服务分配storage才会报错

我在自己服务器上测试连接1000次多没有连接失败，可能服务器部署问题

```ruby
if @storage.is_a?(Fastdfs::Client::Storage)
  ...
end
```
